<a href="https://colab.research.google.com/github/sumitt1/pythonall/blob/master/k_nearest_manual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

def find_k_nearest_neighbors(array, value, k):
    # Calculate the absolute differences between the array elements and the value
    differences = np.abs(array - value)

    print(differences)
    # Sort the array indices based on the differences
    sorted_indices = np.argsort(differences)
    print(sorted_indices)
    
    # Get the first k indices (nearest neighbors)
    k_indices = sorted_indices[:k]
    print(k_indices)
   
    # Get the corresponding values from the original array
    nearest_neighbors = array[k_indices]


    return nearest_neighbors

# Example usage
my_array = np.array([1, 5, 10, 15, 20, 25, 30])
my_value = 12
k = 3

nearest_neighbors = find_k_nearest_neighbors(my_array, my_value, k)
print(nearest_neighbors)


[11  7  2  3  8 13 18]
[2 3 1 4 0 5 6]
[2 3 1]
[10 15  5]
